const bodyParts=  { 
    "head": [
        "Headache",
        "Face pain",
        "Sinus Pain or pressure",
        "Fever",
        "Swollen Face",
        "Facial muscle weakness",
        "Face tingling or numbness",
        "Loss of counsciousness",
        "Impaired memory",
        "Feeling sick or queasy",
        "Hair loss",
        "Skin changes on the face",
        "Recent head injury",
    ],
    "shoulder": [
        "Shoulder pain",
        "Pain when moving the shoulder",
        "Swollen shoulder",
    ],
    "cheast": [
        "Breast enlargement in man",
        "Chest pain",
        "Chest pain, spreading to the left upper limb",
        "Pressing chest pain",
        "Palpitations",
        "Heartburn",
        "Fast heart rate",
        "Slow heart rate",
        "Cough",
        "Shortness of breath",
        "Shallow breathing",
        "Accelerated breathing",
        "Whistling sound made while breathing",
        "Chest injury",
    ],
    "arm": [
        "Pain in forearm",
        "Swollen elbow",
        "Swollen wrist",
        "Wrist pain",
        "Pain when moving the wrist",
        "Elbow pain",
        "Pain when moving the elbow",
        "Dropping hand",
        "Loss of feeling in both arms",
        "Forearm injury",
        "Arm injury",
        "Spasms in arms or hands",
        "Loss of feeling in both arms",
    ],
    "legs": [
        "Pain in lower limb",
        "Severe pain in lower limb",
        "Thight pain",
        "Hip pain",
        "Pain when moving hip",
        "Lower back pain spreading to the back of the thigh or knee",
        "Limping due to pain",
        "Acute thigh or buttock pain appearing during exertion and relieving after short rest",
        "Pain when pressing lower limb",
        "Hip swelling",
        "Swollen legs",
        "Tingling or numbness in one lower limb",
        "Red stretch marks on stomach, hips, or thighs",
        "Tingling or numbness of both lower limbs",
        "Thigh injury",
        "Pain in one knee",
        "Pain when moving knee",
        "Pain when pressing joint",
        "Stiff joints",
        "Swollen knee",
        "Slower walk",
        "Creaking joints during movement",
        "Knee injury",
        "Pain in both lower limbs",
        "Pain when pressing calf",
        "Pain in calf",
        "Severe pain in calf while walking",
        "Lower leg injury",
        "Heavy legs at the end of the day",
        "Loss of feeling in one Am or leg",
        "Pain in one foot",
        "Toe pain",
        "Sore nail",
        "Pain of the skin around the nail",
        "Ankle pain",
        "Big toe pain",
        "Feet tingling or numbness",
        "Swollen feet",
        "Swollen toe",
        "Skin changes on feet",
        "Thickened nails",
        "Enlarged fingertips and nails",
        "Brown nail discolouration",
        "White spots on nail",
        "Yellow nails",
        "Cold feet and toes",
        "Dropping the front of the foot",
        "Toe injury",
        "Foot injury",
        "Pain in both feet"
    ],
    "hands": [
        "Pain in both feet",
        "Wrist pain",
        "Pain when moving wrist",
        "Pain in hand or fingers",
        "Pain in one finger",
        "Pain of the skin around the nail",
        "Swollen hand",
        "Swollen wrist",
        "Swollen finger",
        "Skin changes on hands",
        "Red hand",
        "Greyish-blue fingers",
        "Red skin on palms",
        "Tingling fingers",
        "Trembling of both hands",
        "Trembling of one hand",
        "Loss of muscles in hands",
        "Stiff hands in the morning",
        "Cold hands or fingers",
        "Hand injury"
    ],
    "stomach": [
        "Stomach pain",
        "Central stomach pain",
        "Burning or gnawing stomach pain",
        "olic stomach pain",
        "Crampy stomach pain",
        "Sharp and stabbing stomach pain",
        "Pain when pressing the stomach",
        "Lump in stomach",
        "Increased abdominal size",
        "Bloating",
        "Constipation",
        "Diarrhea",
        "Vomiting",
        "Feeling sick or queasy",
        "Black stool",
        "Red stool",
        "Recent abdominal injury"
    ] 
}


export default bodyParts;
